package turn

import (
	"context"
	"strings"
	"sync"
	"time"

	"github.com/trick77/loom/internal/background"
	"github.com/trick77/loom/internal/llm"
)

// reasoningTitleTimeout bounds a single background title call. Wait() blocks the
// final assistant_message on outstanding title goroutines and the shared HTTP
// client has no timeout, so without this a hung title call would stall delivery.
const reasoningTitleTimeout = 10 * time.Second

// ReasoningTitleHold bounds how long the first answer word waits for its
// round's title (see streamAssistantTurnWithContentStreaming). Measured on a
// short thinker the title lands ~2.7s after reasoning ends; a title call on a
// dead upstream must not hold the answer, or the turn's error, much past that.
// A var so tests can shorten it.
var ReasoningTitleHold = 5 * time.Second

// ReasoningTitleStartBytes is how much of a round's reasoning must have
// streamed before its title generates. The title names the subject, which the
// opening of the reasoning already carries, so it need not wait for the model
// to stop thinking: that wait kept the first sweep line off screen for the
// whole thinking phase, and past the first answer words whenever the title
// call was slower than ReasoningTitleHold. A round with less reasoning is
// titled at its end, as before. A var so tests can shorten it.
var ReasoningTitleStartBytes = 300

// ReasoningTitleTracker generates a short abstract title for each reasoning
// round in the background. Titles are emitted over SSE as they become ready and
// collected so they can be merged into the persisted activity trace. The zero
// value is not usable; build one with NewReasoningTitleTracker.
type ReasoningTitleTracker struct {
	client   ChatClient
	stream   Emitter
	ctx      context.Context
	inf      llm.InferenceMetadata
	language string // user's response language; "" for the English default
	wg       sync.WaitGroup
	// working tracks the working-title call apart from wg: Wait() gates the
	// answer on the reasoning titles, and the working title is worthless once
	// the answer exists, so only the stream's teardown waits for it.
	working sync.WaitGroup
	mu      sync.Mutex
	titles  map[string]string // reasoning id -> title
	spawned map[string]bool   // reasoning id -> already generating
}

// NewReasoningTitleTracker returns a tracker whose titles are generated by
// client, bounded by ctx, and emitted to stream.
func NewReasoningTitleTracker(ctx context.Context, client ChatClient, stream Emitter, inf llm.InferenceMetadata, language string) *ReasoningTitleTracker {
	return &ReasoningTitleTracker{client: client, stream: stream, ctx: ctx, inf: inf, language: language, titles: map[string]string{}, spawned: map[string]bool{}}
}

// spawn kicks off a background title generation for one reasoning round. It is a
// no-op when there is no reasoning id or no reasoning content, and is idempotent
// per id so the mid-turn boundary and the post-turn fallback never double-fire.
// The caller must eventually call Wait() before tearing down the stream.
//
// The returned channel closes once the title has gone out or been skipped (nil
// when nothing was spawned), so a caller can hold the answer behind it.
func (t *ReasoningTitleTracker) spawn(reasoningID, reasoning string) <-chan struct{} {
	if t == nil || reasoningID == "" || strings.TrimSpace(reasoning) == "" {
		return nil
	}
	t.mu.Lock()
	if t.spawned[reasoningID] {
		t.mu.Unlock()
		return nil
	}
	t.spawned[reasoningID] = true
	t.mu.Unlock()
	t.wg.Add(1)
	done := make(chan struct{})
	go func() {
		defer t.wg.Done()
		defer close(done)
		// Outside the handler chain the recovery middleware can't catch a panic
		// here, and one would take the process down mid-stream.
		defer background.LogPanic("reasoning_title")
		inf := t.inf
		inf.Purpose = "reasoning_title"
		// Bound the call so a hung title request can never delay delivery of the
		// final answer: Wait() blocks assistant_message on this goroutine, and the
		// shared HTTP client has no timeout. On timeout the title is simply skipped.
		ctx, cancel := context.WithTimeout(t.ctx, reasoningTitleTimeout)
		defer cancel()
		title, err := t.client.GenerateReasoningTitle(llm.WithInferenceMetadata(ctx, inf), reasoning, t.language)
		if err != nil || strings.TrimSpace(title) == "" {
			return
		}
		t.mu.Lock()
		t.titles[reasoningID] = title
		t.mu.Unlock()
		_ = t.stream.Send("assistant_reasoning_title", ReasoningTitleResponse{ID: reasoningID, Title: title})
	}()
	return done
}

// WorkingTitleResponse is the payload of assistant_working_title.
type WorkingTitleResponse struct {
	Title string `json:"title"`
}

// SpawnWorking kicks off the turn's first sweep line, generated from the
// user's message the moment it is sent. The reasoning titles need reasoning to
// exist; before any does, the reader would see nothing but the dots through
// the pre-answer gates and the model's first seconds. The client shows it until
// the first reasoning title replaces it. It is never persisted. The caller must
// eventually call WaitWorking() before tearing down the stream.
func (t *ReasoningTitleTracker) SpawnWorking(userMessage string) {
	if t == nil || strings.TrimSpace(userMessage) == "" {
		return
	}
	t.working.Add(1)
	go func() {
		defer t.working.Done()
		defer background.LogPanic("working_title")
		inf := t.inf
		inf.Purpose = "working_title"
		ctx, cancel := context.WithTimeout(t.ctx, reasoningTitleTimeout)
		defer cancel()
		title, err := t.client.GenerateWorkingTitle(llm.WithInferenceMetadata(ctx, inf), userMessage, t.language)
		if err != nil || strings.TrimSpace(title) == "" {
			return
		}
		_ = t.stream.Send("assistant_working_title", WorkingTitleResponse{Title: title})
	}()
}

// WaitWorking blocks until the working-title call has finished.
func (t *ReasoningTitleTracker) WaitWorking() {
	if t == nil {
		return
	}
	t.working.Wait()
}

// Wait blocks until every spawned title goroutine has finished.
func (t *ReasoningTitleTracker) Wait() {
	if t == nil {
		return
	}
	t.wg.Wait()
}

// MergeInto stamps collected titles onto their matching reasoning events. Call
// after Wait() so the persisted trace carries the titles.
func (t *ReasoningTitleTracker) MergeInto(trace []ActivityTraceEvent) {
	if t == nil {
		return
	}
	t.mu.Lock()
	defer t.mu.Unlock()
	t.stampTitles(trace)
}

// MergeIntoBlocks stamps collected titles onto the reasoning events inside every
// trace block. The blocks' trace events are separate objects from the flat
// trace, but share the same reasoning-event ids, so the same title map applies.
func (t *ReasoningTitleTracker) MergeIntoBlocks(blocks []ContentBlock) {
	if t == nil {
		return
	}
	t.mu.Lock()
	defer t.mu.Unlock()
	for i := range blocks {
		if blocks[i].Type != "trace" {
			continue
		}
		t.stampTitles(blocks[i].Events)
	}
}

// stampTitles writes each collected title onto its matching reasoning event.
// Callers must hold t.mu.
func (t *ReasoningTitleTracker) stampTitles(events []ActivityTraceEvent) {
	for i := range events {
		if events[i].Type != "reasoning" {
			continue
		}
		if title, ok := t.titles[events[i].ID]; ok {
			events[i].Title = title
		}
	}
}

// ReasoningTitleResponse is the payload of assistant_reasoning_title.
type ReasoningTitleResponse struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}
