package llm

import (
	"context"
	"encoding/base64"
	"fmt"
	"strings"
	"time"

	"github.com/trick77/llmwire"
	"github.com/trick77/loom/internal/imagescale"
	"github.com/trick77/loom/internal/inference"
)

// imageDescribeMaxCompletionTokens caps the vision description. At the helper
// effort nearly the whole budget goes to the description itself, so a few dense
// paragraphs incl. transcribed text fit in 2048.
const imageDescribeMaxCompletionTokens = 2048

// imageDescribeTimeout bounds a single description call. Ingest runs detached
// (context.WithoutCancel) and main passes an untimed http client, so without this
// a stalled vision turn would hang the ingest goroutine indefinitely.
const imageDescribeTimeout = 2 * time.Minute

const imageDescribeInstruction = "Describe this image in detail for a search index. " +
	"Cover the main subjects, scene, layout, colors, and any visible or legible text " +
	"verbatim. Write plain descriptive prose with no preamble, no markdown, and no questions."

// DescribeImage returns a dense plain-text description of an image, generated by
// the vision model, for indexing the image as RAG knowledge. The text-only model
// 404s on image input, so this forces visionModel explicitly. The image is
// downscaled (imagescale) before being inlined as a base64 data URL.
func (c *Client) DescribeImage(ctx context.Context, data []byte, mime string) (string, error) {
	// Tag the call even when it runs from a path that attached no metadata (a
	// detached ingest goroutine), so the log line is never an anonymous
	// vision-model call.
	ctx = inference.WithDefaultPurpose(ctx, "image_describe")
	ctx, cancel := context.WithTimeout(ctx, imageDescribeTimeout)
	defer cancel()

	encoded, encodedMIME := imagescale.DownscaleForModel(data, mime)
	dataURL := "data:" + encodedMIME + ";base64," + base64.StdEncoding.EncodeToString(encoded)

	messages := []Message{{
		Role: "user",
		ContentParts: []MessageContentPart{
			{Type: "image_url", ImageURL: &MessageImageURL{URL: dataURL}},
			{Type: "text", Text: imageDescribeInstruction},
		},
	}}

	// The helper effort mirrors the title utility: deep thinking overthinks the
	// task and burns the token budget on reasoning (risking
	// finish_reason=length). Describing is perception + transcription, not
	// reasoning.
	reply, err := c.complete(ctx, c.visionModel, messages, imageDescribeMaxCompletionTokens, llmwire.ReasoningMinimal(), nil)
	if err != nil {
		return "", err
	}
	if reply.Empty {
		return "", fmt.Errorf("image description returned no choices")
	}
	text := strings.TrimSpace(reply.Content)
	if text == "" {
		// Empty content (e.g. finish_reason=length, or the model emitted only a
		// channel marker) → surface a clear error so ingest records status=error
		// instead of embedding nothing.
		return "", fmt.Errorf("image description was empty (finish_reason=%q)", reply.FinishReason)
	}
	return text, nil
}
