package llm

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/trick77/slopr/internal/imagescale"
)

// imageDescribeMaxCompletionTokens caps the vision description. With thinking
// disabled the whole budget goes to the description itself, so a few dense
// paragraphs incl. transcribed text fit in 2048 — well under MiMo's 131072 limit.
const imageDescribeMaxCompletionTokens = 2048

// imageDescribeTimeout bounds a single description call. Ingest runs detached
// (context.WithoutCancel) and main passes an untimed http client, so without this
// a stalled vision turn would hang the ingest goroutine indefinitely.
const imageDescribeTimeout = 2 * time.Minute

const imageDescribeInstruction = "Describe this image in detail for a search index. " +
	"Cover the main subjects, scene, layout, colors, and any visible or legible text " +
	"verbatim. Write plain descriptive prose with no preamble, no markdown, and no questions."

// DescribeImage returns a dense plain-text description of an image, generated by
// the vision model, for indexing the image as RAG knowledge. The text-only model
// 404s on image input, so this forces visionModel explicitly. The image is
// downscaled (imagescale) before being inlined as a base64 data URL.
func (c *Client) DescribeImage(ctx context.Context, data []byte, mime string) (string, error) {
	start := time.Now()
	ctx, cancel := context.WithTimeout(ctx, imageDescribeTimeout)
	defer cancel()

	encoded, encodedMIME := imagescale.DownscaleForModel(data, mime)
	dataURL := "data:" + encodedMIME + ";base64," + base64.StdEncoding.EncodeToString(encoded)

	messages := []Message{{
		Role: "user",
		ContentParts: []MessageContentPart{
			{Type: "image_url", ImageURL: &MessageImageURL{URL: dataURL}},
			{Type: "text", Text: imageDescribeInstruction},
		},
	}}

	// Thinking disabled mirrors the title utility: MiMo otherwise overthinks the
	// task, burns the token budget on reasoning (risking finish_reason=length),
	// and can echo its internal reasoning/response channel markers as literal text
	// — which would poison the stored description. Describing is perception +
	// transcription, not reasoning.
	resp, err := c.executeChatRequestImpl(ctx, messages, chatRequestOptions{
		model:               c.visionModel,
		thinking:            &thinkingOption{Type: "disabled"},
		maxCompletionTokens: imageDescribeMaxCompletionTokens,
	})
	if err != nil {
		logInferenceFailed(ctx, c.visionModel, time.Since(start), err)
		return "", err
	}
	defer resp.Body.Close()

	var completion chatCompletionResponse
	if err := json.NewDecoder(resp.Body).Decode(&completion); err != nil {
		err := fmt.Errorf("decode image description response: %w", err)
		logInferenceFailed(ctx, c.visionModel, time.Since(start), err)
		return "", err
	}
	if len(completion.Choices) == 0 {
		observeInference(ctx, c.visionModel, time.Since(start), completion.Usage, "")
		return "", fmt.Errorf("image description returned no choices")
	}
	choice := completion.Choices[0]
	observeInference(ctx, c.visionModel, time.Since(start), completion.Usage, choice.FinishReason)
	text := strings.TrimSpace(choice.Message.Content)
	if text == "" {
		// Empty content (e.g. finish_reason=length, or the model emitted only a
		// channel marker) → surface a clear error so ingest records status=error
		// instead of embedding nothing.
		return "", fmt.Errorf("image description was empty (finish_reason=%q)", choice.FinishReason)
	}
	return text, nil
}
